### ISSUE TITLE
compliance_report doesn't support several ping targets

### ISSUE THREAD

**Issue by XioNoX** [napalm-automation/napalm-base#180]
Currently, if the validate.yml file contains several ping statements

```
ping:
  _kwargs:
      destination: 8.8.8.8
      source: 192.168.1.1
  success:
      packet_loss: 0
  _mode: strict

ping:
  _kwargs:
      destination: 4.4.2.2
      source: 192.168.1.1
  success:
      packet_loss: 0
  _mode: strict
```
The end result will only consider one of the two:
```
            "ping": {
                "complies": true, 
                "extra": [], 
                "missing": [], 
                "present": {
                    "success": {
                        "complies": true, 
                        "nested": true
                    }
                }
            }
```

It would be useful to be able to test many different ping tasks for a given host. The same might apply to traceroute.

**Comment by dbarrosop** [comment]
@napalm-automation/council

I see two options here:

1. Replace the key with a name. Something like:

```
test_pinging_google_dns:
	ping:
	  _kwargs:
	      destination: 8.8.8.8
	      source: 192.168.1.1
	  success:
	      packet_loss: 0
	  _mode: strict

test_pinging_other_google_dns:
	ping:
	  _kwargs:
	      destination: 4.4.2.2
	      source: 192.168.1.1
	  success:
	      packet_loss: 0
	  _mode: strict
```

2. composing the keys to be able to add a key (separting command and description with two `_`:

```
ping__google_dns:
  _kwargs:
      destination: 8.8.8.8
      source: 192.168.1.1
  success:
      packet_loss: 0
  _mode: strict

ping__other_google_dns:
  _kwargs:
      destination: 4.4.2.2
      source: 192.168.1.1
  success:
      packet_loss: 0
  _mode: strict
```

I personally prefer the second option but I am open to suggestions/opinions.

**Comment by mirceaulinic** [comment]
@dbarrosop I do find the first option _much_ cleaner. I personally want to avoid hacks as in the second one.

**Comment by dbarrosop** [comment]
There are actually two reasons I like the second method:

1. Most methods don't require a name as it doesn't make sense to execute two time `get_facts` or `get_bgp_neighbors`. Name only makes sense on methods that uses arguments.
2. Using `ping__blah` serves as a key on the report as well.

Maybe we can do someting like:

```
get_facts:
   os_version: blah

ping:
  _name: google dns
  _kwargs:
      destination: 8.8.8.8
      source: 192.168.1.1
  success:
      packet_loss: 0
  _mode: strict

ping
  _name: other google dns
  _kwargs:
      destination: 4.4.2.2
      source: 192.168.1.1
  success:
      packet_loss: 0
  _mode: strict
```

And then in the report us the `_name` as a subkey if present. For example:

```
get_facts:
   # here goes the report for get_facts
ping:
   "google dns":
      # here goes the report for the first ping
   "other google dns":
      # here goes the report for the second ping
```

Or do we really think the name is useful and should be the primary key?

**Comment by XioNoX** [comment]
Note that this needs to be applied to at least "get_route_to", "traceroute", and most likely others.

**Comment by dbarrosop** [comment]
@XioNoX can you review #191?

**Comment by XioNoX** [comment]
@dbarrosop works fine for me!
Thanks

**Comment by XioNoX** [comment]
After more testing, it seems like if there are several getters used with a different `_name`, it will only execute (or at least display) one.

For example if I define:
```
get_route_to:
  _name: vpn-v4
  _kwargs:
    destination: 10.0.0.0/8
  "10.0.0.0/8":
    list:
     - next_hop: 10.0.239.130
       protocol: "bgp"
       current_active: true

get_route_to:
  _name: core-v4
  _kwargs:
    destination: 10.239.24.0/21
  "10.239.24.0/21":
    list:
     - next_hop: 10.239.255.2
       protocol: "bgp"
       current_active: true
```
The output after running it through the ansible module will be:
```
ok: [mydevice] => {
    "changed": false, 
    "compliance_report": {
        "complies": true, 
        "core-v4": {
            "complies": true, 
            "extra": [], 
            "missing": [], 
            "present": {
                "10.239.24.0/21": {
                    "complies": true, 
                    "nested": true
                }
            }
        }, 
        "get_lldp_neighbors": {
            redacted, not related.
        }, 
        "skipped": []
    }, 
```
And thus, the one with `_name: vpn-v4` isn't present.
