### ISSUE TITLE
Adding functions for get_vlans and get_interface_descriptions()

### ISSUE THREAD

**Issue by icmp-echo** [napalm-automation/napalm-base#252]
So today there are the following methods in napalm-base

get_arp_table ()
get_mac_address_table()
get_interfaces_ip()
get_interfaces_counters()
get_interfaces()	

As a network operations center and as an engineer I  heavily rely on basic information of vlans and interface description find the right port or right unit, and could use similar functionality.  So my proposal is to add:

get_vlans()
get_interfaces_descriptions()

which is very basic but could impact very very positively.

Thanks

**Comment by dbarrosop** [comment]
Hi,
regarding `get_interfaces_description`, do you see something here that might be missing on `get_interfaces`? You should have the description there already.

Regarding `get_vlan`, I'd propose a method that returns an openconfig-like object:

```
vlans:
  vlan:
    1:
      config:
          name: default
          status: active|suspended
    3:
      config:
          name: pre
          status: active|suspended
   4:
      config:
          name: pro
          status: ACTIVE|SUSPENDED
 interfaces:
   interface:
      et1:
        ethernet:
             switched-vlan:
                 config:
                       interface-mode: ACCESS|TRUNK
                       native-vlan: 1
                       access-vlan: 3
                       trunk-vlans: [3,4]
```

It's not the nicest model but it's similar to how OC looks like and will allow us to reuse code for `napalm-yang`. Thoughts?

@mirceaulinic ^
